version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: git@github.com:RunnableDemo/node-starter.git#master
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
