version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    image: redis
    ports:
      - "3000:3000"
    links:
      - "db:db"
    environment:
      - MONGODB_HOST=db
